spring.application.name=cadastro-jogadores
spring.thymeleaf.cache=false
# CONFIGURANDO BD
spring.sql.init.mode=always

# CONFIUGURANDO H2
spring.datasource.url=jdbc:h2:file:./data/jogadores
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
